name: 'setup_node-cache_dep-install_dep'
description: 'Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js ⚙️ & Cache dependencies ⚡
      uses: actions/setup-node@v4
      with:
        node-version: '20.12.2'
        cache: 'yarn'
        cache-dependency-path: ./yarn.lock

    - name: Install dependencies 🔧
      shell: bash
      run: yarn install --frozen-lockfile --non-interactive
