name: pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

  FILE_PATH_WEB_BUILD: ./apps/web/dist/build/.next
  FILE_PATH_UI_BUILD: ./packages/ui/dist/storybook

  CACHE_PATHS_BUILD: |
    ./apps/web/dist/build/.next
    ./packages/ui/dist/storybook
  CACHE_KEY_BUILD: build-${{ github.sha }}-${{ github.ref_type }}
  CACHE_RESTORE_KEYS: build-
  
jobs:
  install:
    name: Install packages 🔧
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

  type-check:
    name: Compile 🔎
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

      - name: TypeScript Compiler 🔎
        run: yarn type-check

  lint:
    name: Lint ✅
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

      - name: Lint ✅
        run: yarn lint

  build:
    name: Build 🏗️
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

      - name: Build 🏗️
        run: |
          yarn build
          yarn storybook-build

      - name: Cache build ⚡
        id: cache_build
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_PATHS_BUILD }}
          key: ${{ env.CACHE_KEY_BUILD }}
          restore-keys: ${{ env.CACHE_RESTORE_KEYS }}

  test:
    name: Test 🧪
    needs: [type-check, lint, build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

      - name: Test 🧪
        run: yarn test --coverage

  sonarcloud:
    name: Sonar Cloud 👍
    needs: [type-check, lint, build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: SonarCloud Scan 👍
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}